= Funcool
:toc: right
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

*funcool* is a growing collection of open source Clojure and ClojureScript libraries that
sares this principes:

- Good documentation.
- Clear state of development.
- Easy way to contribute.
- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

Clojure has a very good community and has very good libraries for do almost everything and majority
of them are not known, but also it has much more libraries that are undocumented, unmantained or with
very bad implementation.

We will try to maintain a little collection of libraries developed by ourselves and also
maintain an arbitrary updated list of currently maintained libraries that we have used in the past
or actualy using for our projects.


== Who is responsible for it?

*funcool* is a little comunity managed by a little group of persons that loves functional
programming and good and well documented open source software.

You can contact us using *funcool* google groups: https://groups.google.com/forum/#!forum/funcool


== Libraries developed by us

=== buddy

*buddy* is a complete security library for clojure.

- Github: https://github.com/niwibe/buddy
- Documentation: https://niwibe.github.io/buddy/


=== cats

Category Theory abstractions for Clojure.

- Github: https://github.com/funcool/cats
- Documentation: http://niwibe.github.io/cats/


=== suricatta

High level sql toolkit for clojure (backed by jooq library)

- Github: https://github.com/niwibe/suricatta
- Documentation: http://niwibe.github.io/suricatta/


=== clojure.jdbc

_clojure.jdbc_ is a library for low level, jdbc-based database access.

Is an alternative implementation to the official `clojure.java.jdbc`.

- Github: https://github.com/niwibe/clojure.jdbc
- Documentation: http://niwibe.github.io/clojure.jdbc/


=== hodgepodge

A idiomatic ClojureScript interface to local and session storage.

- Github: https://github.com/dialelo/hodgepodge
- Documentation: https://dialelo.github.io/hodgepodge/

=== cuerdas

The missing clojurescript string manipulation library.

- Github & Documentation: https://github.com/funcool/cuerdas


== Third party libraries for Clojure

=== cheshire

Clojure JSON and JSON SMILE (binary json format) encoding/decoding.

- Github & Documentation: https://github.com/dakrone/cheshire


=== clj-time

A date and time library for Clojure, wrapping the Joda Time library.

- Github & Documentation: https://github.com/clj-time/clj-time


=== potemkin

Potemkin is a collection of facades and workarounds for things that are more difficult
than they should be.

- Github & Documentation: https://github.com/ztellman/potemkin

=== nippy

Clojure serialization library

- Github & Documentation: https://github.com/ptaoussanis/nippy


=== jet

Jetty9 ring server adapter with WebSocket support via core.async and Jetty9 based
HTTP & WebSocket clients.

- Github & Documentation: https://github.com/mpenet/jet


=== nomad

A Clojure library designed to allow Clojure configuration to travel between hosts.

- Github & Documentation: https://github.com/james-henderson/nomad


=== ring

Clojure HTTP server abstraction

- Github & Documentation: https://github.com/ring-clojure/ring


=== compojure

A concise routing library for Ring/Clojure

- Github & Documentation: https://github.com/weavejester/compojure


=== clout

HTTP route-matching library for Clojure

- Github & Documentation: https://github.com/weavejester/clout


=== hiccup

Fast library for rendering HTML in Clojure

- Github & Documentation: https://github.com/weavejester/hiccup


== Third party libraries for ClojureScript

=== secretary

A client-side router for ClojureScript.

- Github & Documentation: https://github.com/gf3/secretary


=== shodan

A ClojureScript library providing wrappers for the JavaScript console API.

- Github & Documentation: https://github.com/noprompt/shodan


=== hipo

A ClojureScript DOM templating library based on hiccup syntax

- Github & Documentation: https://github.com/jeluard/hipo/


=== dommy

A ClojureScript DOM manipulation and event library.

- Github & Documentation: https://github.com/Prismatic/dommy

=== om

ClojureScript interface to Facebook's React

- Github & Documentation: https://github.com/swannodette/om


=== sablono

Lisp/Hiccup style templating for Facebook's React in ClojureScript.

- Github & Documentation: https://github.com/r0man/sablono


== Third party libraries for both: Clojure and ClojureScript

=== schema

Clojure(Script) library for declarative data description and validation

- Github & Documentation: https://github.com/Prismatic/schema


=== speclj

It's a TDD/BDD framework for Clojure and Clojurescript, based on RSpec.

- Github & Documentation: https://github.com/slagyr/speclj