= Funcool
:toc: right
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

*funcool* is a growing collection of open source Clojure and ClojureScript libraries that
share the following principles:

- Good documentation.
- Clear state of development.
- Easy way to contribute.
- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

Clojure has a very good community and has very good libraries for doing almost everything and the majority
aren't known. On the other hand there are also libraries that are undocumented, unmantained or with
a very bad implementation.

We will try to maintain a little collection of libraries developed by ourselves and also
another list of well maintained libraries that we have used in the past or are currently
using for our projects.


== Who is responsible for it?

*funcool* is a community managed by a little group of persons that loves functional
programming and good, well documented open source software.

You can contact us using *funcool* google groups: https://groups.google.com/forum/#!forum/funcool


== Libraries developed by us

=== buddy

*buddy* is a complete security library for clojure.

- Github: https://github.com/funcool/buddy
- Documentation: https://funcool.github.io/buddy/


=== cats

Category Theory abstractions for Clojure.

- Github: https://github.com/funcool/cats
- Documentation: http://funcool.github.io/cats/


=== suricatta

High level sql toolkit for clojure (backed by jooq library)

- Github: https://github.com/funcool/suricatta
- Documentation: http://funcool.github.io/suricatta/


=== clojure.jdbc

_clojure.jdbc_ is a library for low level, jdbc-based database access.

Is an alternative implementation to the official `clojure.java.jdbc`.

- Github: https://github.com/funcool/clojure.jdbc
- Documentation: http://funcool.github.io/clojure.jdbc/


=== hodgepodge

A idiomatic ClojureScript interface to local and session storage.

- Github: https://github.com/funcool/hodgepodge
- Documentation: https://funcool.github.io/hodgepodge/

=== cuerdas

The missing clojurescript string manipulation library.

- Github & Documentation: https://github.com/funcool/cuerdas


== Third party libraries for Clojure

=== cheshire

Clojure JSON and JSON SMILE (binary json format) encoding/decoding.

- Github & Documentation: https://github.com/dakrone/cheshire


=== clj-time

A date and time library for Clojure, wrapping the Joda Time library.

- Github & Documentation: https://github.com/clj-time/clj-time


=== potemkin

Potemkin is a collection of facades and workarounds for things that are more difficult
than they should be.

- Github & Documentation: https://github.com/ztellman/potemkin

=== nippy

Clojure serialization library

- Github & Documentation: https://github.com/ptaoussanis/nippy


=== jet

Jetty9 ring server adapter with WebSocket support via core.async and Jetty9 based
HTTP & WebSocket clients.

- Github & Documentation: https://github.com/mpenet/jet


=== nomad

A Clojure library designed to allow Clojure configuration to travel between hosts.

- Github & Documentation: https://github.com/james-henderson/nomad


=== ring

Clojure HTTP server abstraction

- Github & Documentation: https://github.com/ring-clojure/ring


=== compojure

A concise routing library for Ring/Clojure

- Github & Documentation: https://github.com/weavejester/compojure


=== clout

HTTP route-matching library for Clojure

- Github & Documentation: https://github.com/weavejester/clout


=== hiccup

Fast library for rendering HTML in Clojure

- Github & Documentation: https://github.com/weavejester/hiccup


== Third party libraries for ClojureScript

=== secretary

A client-side router for ClojureScript.

- Github & Documentation: https://github.com/gf3/secretary


=== shodan

A ClojureScript library providing wrappers for the JavaScript console API.

- Github & Documentation: https://github.com/noprompt/shodan


=== hipo

A ClojureScript DOM templating library based on hiccup syntax

- Github & Documentation: https://github.com/jeluard/hipo/


=== dommy

A ClojureScript DOM manipulation and event library.

- Github & Documentation: https://github.com/Prismatic/dommy


=== om

ClojureScript interface to Facebook's React

- Github & Documentation: https://github.com/swannodette/om


=== sablono

Lisp/Hiccup style templating for Facebook's React in ClojureScript.

- Github & Documentation: https://github.com/r0man/sablono


== Third party libraries for both Clojure and ClojureScript

=== schema

Clojure(Script) library for declarative data description and validation

- Github & Documentation: https://github.com/Prismatic/schema


=== speclj

A TDD/BDD framework for Clojure and Clojurescript, based on RSpec.

- Github & Documentation: https://github.com/slagyr/speclj